package server
import "net/http"
func(s *Server)dashboard(w http.ResponseWriter,r *http.Request){w.Header().Set("Content-Type","text/html; charset=utf-8");w.Write([]byte(dashHTML))}
const dashHTML=`<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cutoff</title>
<style>:root{--bg:#1a1410;--bg2:#241e18;--bg3:#2e261e;--rust:#c45d2c;--rl:#e8753a;--leather:#a0845c;--cream:#f0e6d3;--cd:#bfb5a3;--cm:#7a7060;--gold:#d4a843;--green:#4a9e5c;--red:#c44040;--mono:'JetBrains Mono',Consolas,monospace;--serif:'Libre Baskerville',Georgia,serif}*{margin:0;padding:0;box-sizing:border-box}body{background:var(--bg);color:var(--cream);font-family:var(--mono);font-size:13px;line-height:1.6}.hdr{padding:.6rem 1.2rem;border-bottom:1px solid var(--bg3);display:flex;justify-content:space-between;align-items:center}.hdr h1{font-family:var(--serif);font-size:1rem}.hdr h1 span{color:var(--rl)}.main{max-width:700px;margin:0 auto;padding:1rem}.btn{font-family:var(--mono);font-size:.68rem;padding:.3rem .6rem;border:1px solid;cursor:pointer;background:transparent}.btn-p{border-color:var(--rust);color:var(--rl)}.btn-p:hover{background:var(--rust);color:var(--cream)}.rule-row{display:flex;align-items:center;gap:.6rem;padding:.5rem;background:var(--bg2);border:1px solid var(--bg3);margin-bottom:.3rem}.rule-name{flex:1;font-weight:600}.rule-limit{font-size:.75rem;color:var(--gold)}.rule-window{font-size:.65rem;color:var(--cm)}.toggle{width:36px;height:20px;border-radius:10px;cursor:pointer;position:relative;transition:.2s}.toggle.on{background:var(--green)}.toggle.off{background:var(--bg3)}.toggle::after{content:'';width:16px;height:16px;border-radius:50%;background:var(--cream);position:absolute;top:2px;left:2px;transition:.2s}.toggle.on::after{left:18px}.empty{text-align:center;padding:2rem;color:var(--cm);font-style:italic;font-family:var(--serif)}.modal-bg{position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,.65);display:flex;align-items:center;justify-content:center;z-index:100}.modal{background:var(--bg2);border:1px solid var(--bg3);padding:1.5rem;width:90%;max-width:450px}.modal h2{font-family:var(--serif);font-size:.9rem;margin-bottom:1rem}label.fl{display:block;font-size:.65rem;color:var(--leather);text-transform:uppercase;letter-spacing:1px;margin-bottom:.2rem;margin-top:.5rem}input[type=text],input[type=number],select{background:var(--bg);border:1px solid var(--bg3);color:var(--cream);padding:.35rem .5rem;font-family:var(--mono);font-size:.78rem;width:100%;outline:none}.form-row{display:flex;gap:.5rem}.form-row>*{flex:1}</style>
<link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital@0;1&family=JetBrains+Mono:wght@400;600&display=swap" rel="stylesheet">
</head><body><div class="hdr"><h1><span>Cutoff</span></h1><button class="btn btn-p" onclick="showNew()">+ Rule</button></div>
<div class="main"><div id="list"></div></div><div id="modal"></div>
<script>
async function api(u,o){return(await fetch(u,o)).json()}
function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
async function load(){const d=await api('/api/rules');const rules=d.rules||[];
document.getElementById('list').innerHTML=rules.length?rules.map(r=>'<div class="rule-row"><div class="toggle '+(r.enabled?'on':'off')+'" onclick="toggle(\''+r.id+'\')"></div><span class="rule-name">'+esc(r.name)+'</span><span class="rule-limit">'+r.limit+' req</span><span class="rule-window">/ '+r.window_sec+'s</span><span style="font-size:.6rem;color:var(--cm)">'+r.action+'</span><span style="cursor:pointer;font-size:.55rem;color:var(--cm)" onclick="del(\''+r.id+'\')">del</span></div>').join(''):'<div class="empty">No rate limit rules yet. POST /api/check to test limits.</div>'}
async function toggle(id){await api('/api/rules/'+id+'/toggle',{method:'POST'});load()}
async function del(id){await api('/api/rules/'+id,{method:'DELETE'});load()}
function showNew(){document.getElementById('modal').innerHTML='<div class="modal-bg" onclick="if(event.target===this)closeModal()"><div class="modal"><h2>New Rate Limit Rule</h2><label class="fl">Name</label><input type="text" id="nr-name" placeholder="API requests"><div class="form-row"><div><label class="fl">Limit</label><input type="number" id="nr-limit" value="100"></div><div><label class="fl">Window (seconds)</label><input type="number" id="nr-window" value="60"></div></div><label class="fl">Action when exceeded</label><select id="nr-action"><option value="reject">Reject (429)</option><option value="throttle">Throttle</option><option value="log">Log only</option></select><div style="display:flex;gap:.5rem;margin-top:1rem"><button class="btn btn-p" onclick="save()">Create</button><button class="btn" style="border-color:var(--bg3);color:var(--cm)" onclick="closeModal()">Cancel</button></div></div></div>'}
async function save(){const b={name:document.getElementById('nr-name').value,limit:parseInt(document.getElementById('nr-limit').value)||100,window_sec:parseInt(document.getElementById('nr-window').value)||60,action:document.getElementById('nr-action').value};if(!b.name){alert('Name required');return};await api('/api/rules',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});closeModal();load()}
function closeModal(){document.getElementById('modal').innerHTML=''}
load()
</script></body></html>`
