package server

var dashboardHTML = []byte(`<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Stockyard Cutoff</title><style>:root{--bg:#1a1410;--surface:#241c15;--border:#3d2e1e;--rust:#c4622d;--cream:#f5e6c8;--muted:#7a6550;--text:#e8d5b0}*{box-sizing:border-box;margin:0;padding:0}body{background:var(--bg);color:var(--text);font-family:'JetBrains Mono',monospace,sans-serif}header{background:var(--surface);border-bottom:1px solid var(--border);padding:1rem 2rem;display:flex;align-items:center;gap:1rem}.logo{color:var(--rust);font-size:1.25rem;font-weight:700}.badge{background:var(--rust);color:var(--cream);font-size:0.65rem;padding:0.2rem 0.5rem;border-radius:3px;font-weight:600;text-transform:uppercase}main{max-width:900px;margin:0 auto;padding:2rem}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem;margin-bottom:2rem}.stat{background:var(--surface);border:1px solid var(--border);border-radius:6px;padding:1.25rem;text-align:center}.stat-value{font-size:1.75rem;font-weight:700;color:var(--rust)}.stat-label{font-size:0.75rem;color:var(--muted);margin-top:0.25rem;text-transform:uppercase}.card{background:var(--surface);border:1px solid var(--border);border-radius:6px;padding:1.5rem;margin-bottom:1rem}.card h2{font-size:0.85rem;color:var(--muted);text-transform:uppercase;letter-spacing:0.08em;margin-bottom:1rem}.form-row{display:flex;gap:0.5rem;margin-bottom:0.75rem;flex-wrap:wrap}input{background:var(--bg);border:1px solid var(--border);color:var(--text);padding:0.5rem 0.75rem;border-radius:4px;font-family:inherit;font-size:0.85rem;flex:1}.btn{background:var(--rust);color:var(--cream);border:none;padding:0.5rem 1rem;border-radius:4px;cursor:pointer;font-family:inherit;font-size:0.85rem;font-weight:600}.btn:hover{opacity:0.85}.btn-sm{padding:0.25rem 0.6rem;font-size:0.75rem}.btn-danger{background:#7a2020}.btn-outline{background:transparent;border:1px solid var(--rust);color:var(--rust)}table{width:100%;border-collapse:collapse;font-size:0.82rem}th{text-align:left;color:var(--muted);padding:0.5rem;border-bottom:1px solid var(--border);font-size:0.75rem;text-transform:uppercase}td{padding:0.5rem;border-bottom:1px solid var(--border)}.empty{color:var(--muted);font-size:0.85rem;padding:1rem 0;text-align:center}.code-cell{font-family:monospace;color:var(--rust);font-weight:700}.short-url{font-size:0.78rem;color:var(--muted)}.active-dot{color:#5cb85c}.inactive-dot{color:#d9534f}.copy-btn{background:transparent;border:1px solid var(--border);color:var(--muted);padding:0.1rem 0.4rem;border-radius:3px;cursor:pointer;font-size:0.72rem;font-family:inherit}.copy-btn:hover{border-color:var(--rust);color:var(--rust)}</style></head>
<body>
<header><span class="logo">&#x2B21; Stockyard</span><span style="color:var(--muted)">/</span><span style="color:var(--cream);font-weight:600">Cutoff</span><span class="badge">Link Shortener</span></header>
<main>
<div class="stats"><div class="stat"><div class="stat-value" id="s1">0</div><div class="stat-label">Links</div></div><div class="stat"><div class="stat-value" id="s2">0</div><div class="stat-label">Active</div></div><div class="stat"><div class="stat-value" id="s3">0</div><div class="stat-label">Total Clicks</div></div></div>
<div class="card"><h2>Shorten a URL</h2>
<div class="form-row"><input id="f-url" placeholder="https://your-long-url.com/..."><input id="f-code" placeholder="Custom code (optional)" style="max-width:160px"><input id="f-title" placeholder="Label (optional)"><input id="f-exp" type="number" placeholder="Expires in days" style="max-width:140px"></div>
<button class="btn" onclick="createLink()">Shorten</button></div>
<div class="card"><h2>Your Links</h2><div id="link-list"><div class="empty">No links yet</div></div></div>
</main>
<script>
var host=window.location.origin;
function load(){fetch('/api/stats').then(function(r){return r.json()}).then(function(d){document.getElementById('s1').textContent=d.total||0;document.getElementById('s2').textContent=d.active||0;document.getElementById('s3').textContent=d.total_clicks||0})}
function loadLinks(){fetch('/api/links').then(function(r){return r.json()}).then(function(list){var el=document.getElementById('link-list');el.innerHTML=list.length?'<table><thead><tr><th>Code</th><th>Destination</th><th>Title</th><th>Clicks</th><th>Status</th><th></th></tr></thead><tbody>'+list.map(function(l){var shortUrl=host+'/r/'+l.code;return'<tr><td class="code-cell"><a href="/r/'+l.code+'" target="_blank" style="color:var(--rust);text-decoration:none">'+l.code+'</a></td><td style="max-width:220px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:0.78rem;color:var(--muted)">'+l.long_url+'</td><td style="font-size:0.8rem">'+l.title+'</td><td>'+l.clicks+'</td><td>'+(l.active?'<span style="color:#5cb85c">&#x25CF; on</span>':'<span style="color:#d9534f">&#x25CF; off</span>')+'</td><td style="display:flex;gap:0.3rem"><button class="copy-btn" onclick="copy(\''+shortUrl+'\')">copy</button><button class="btn btn-sm btn-outline" onclick="toggle('+l.id+')">'+(l.active?'off':'on')+'</button><button class="btn btn-sm btn-danger" onclick="del('+l.id+')">x</button></td></tr>'}).join('')+"</tbody></table>":'<div class="empty">No links yet. Shorten your first URL above.</div>'})}
function createLink(){var d={long_url:document.getElementById('f-url').value.trim(),code:document.getElementById('f-code').value.trim(),title:document.getElementById('f-title').value.trim(),expires_in_days:parseInt(document.getElementById('f-exp').value)||0};if(!d.long_url)return;if(!d.code)delete d.code;if(!d.expires_in_days)delete d.expires_in_days;fetch('/api/links',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)}).then(function(r){return r.json()}).then(function(l){document.getElementById('f-url').value='';document.getElementById('f-code').value='';document.getElementById('f-title').value='';document.getElementById('f-exp').value='';loadLinks();load()})}
function toggle(id){fetch('/api/links/'+id+'/toggle',{method:'POST'}).then(function(){loadLinks();load()})}
function del(id){fetch('/api/links/'+id,{method:'DELETE'}).then(function(){loadLinks();load()})}
function copy(url){navigator.clipboard.writeText(url).then(function(){},function(){})}
load();loadLinks();
</script></body></html>`)
